language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
  - composer self-update
  - composer install

before_install:
  - sudo pip install codecov

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - composer install --dev

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_success:
  - codecov
